[build]
  # Diretório de build (não necessário para arquivos estáticos)
  publish = "."
  
  # Comando de build (opcional, para processar arquivos se necessário)
  command = "echo 'Build completed'"

[build.environment]
  # Variáveis de ambiente (configure no painel do Netlify)
  # SUPABASE_URL = "sua_url_do_supabase"
  # SUPABASE_ANON_KEY = "sua_chave_anonima_do_supabase"
  # GOOGLE_MAPS_API_KEY = "sua_chave_da_api_do_google_maps"

[[headers]]
  # Configurações de cabeçalho para segurança
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://maps.googleapis.com https://unpkg.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https://maps.gstatic.com https://maps.googleapis.com; connect-src 'self' https://*.supabase.co https://maps.googleapis.com;"

[[redirects]]
  # Redirecionar todas as rotas para index.html (SPA)
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de cache
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
